### ISSUE TITLE
Validate dispatcher valid_dispatch_states on input

### ISSUE THREAD

**Issue by nreinicke** [NREL/hive#104]
I recently added this to the manhattan.yaml scenario file:

```yaml
dispatcher:
  valid_dispatch_states:
    - idle
    - repositioning
    - reserve_base 
```

The model ran without complaint but the true value for `reserve_base` should have been `reservebase`. 

We should validate these inputs and compare them to our list of vehicle state names, only accepting valid names.
